### ISSUE TITLE
issue with configure

### ISSUE THREAD

**Issue by EndlessEden** [archlinuxfr/package-query#146]
i dont have time to debug, but, when building on a archlinux system, with just devtools(gnu toolchain), and base(pacman which includes libalpm), configure fails with the following on line 8771

```
line 8771: syntax error near unexpected token `alpm,'
line 8771: `PKG_CHECK_MODULES(alpm, libalpm >= 12.0.0)'
```
As libalpm is installed, idk if this is related to how it checks for libalpm or if its version incompatibility.
(Pacman version 5.2.1-1)

> I am absolutely exhausted and quite sick. so if im just being a idiot, please do just tell me what the issue is. But i cant find any issue with my systems toolchain.

**Comment by f2404** [comment]
Hmm, did you run `./autogen.sh` before `./configure`?

**Comment by eli-schwartz** [comment]
Your configure script contains the literal text `PKG_CHECK_MODULES(alpm, libalpm >= 12.0.0)` which is a violation of shellscript syntax, because you have an autotools m4 macro in your output. This happens when you run autoreconf -fi/autogen.sh but you don't have the pkg-config program installed (provided by the pkgconf package). If the project provided `make dist` prepared tarballs with a configure script already generated, such that you didn't have to run autoreconf yourself... then configure would still fail, but with a different error -- that error being that the expanded PKG_CHECK_MODULES m4 macro, converted to shellscript, would attempt to invoke the `${PKG_CONFIG:-pkg-config}` binary in order to find the correct cflags/ldflags for linking to libalpm, and fail because pkg-config doesn't exist.

In short, you didn't install the base-devel group as you were expected to do, and you suffered the inevitable fate of anyone who doesn't follow *literally the first rule* of building packages: you got a confusing, nonsensical error.

> when building on a archlinux system, with just devtools(gnu toolchain), and base(pacman which includes libalpm),

I'm completely shocked and bewildered why you have installed devtools as devtools has literally nothing to do with the gnu toolchain. It's just a set of scripts for creating and using [containers](https://en.wikipedia.org/wiki/OS-level_virtualization)! This is a very fundamental conceptual problem with your understanding of how building packages on archlinux works. Please discard everything you think you know and read https://wiki.archlinux.org/index.php/Makepkg instead.

**Comment by EndlessEden** [comment]
Bewildered by tongue-in-cheek, for sure.
Issue was... i do have base-devel package group installed. - i use this chroot specifically for building package-query, but it was probably a issue with git cache as its building fine now. 

Closing; But thanks for the humor :laughing:

**Comment by eli-schwartz** [comment]
Well, that's certainly not the GNU toolchain. :) Either way, however you initially generated the configure script it must not have had pkg-config installed, which implies base-devel was not installed at some point...

And the git cache is not involved since the configure script is not checked into git.
